import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navbar = ["Home", "Catelog", "cart"];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <header className="bg-gray-100 flex justify-between text-center items-center p-2 shadow-lg">
            <div>Logo</div>
            <div className="flex justify-between p-2 cursor-pointer">
              {navbar &&
                navbar.map((item) => {
                  return (
                    <Link
                      className="p-2 font-bold hover:underline hover:text-pink-600"
                      href={item}
                    >
                      {item}
                    </Link>
                  );
                })}
            </div>
            <div className="flex justify-between p-2 cursor-pointer">
              <div className="p-2 font-bold hover:underline hover:text-pink-600">
                Sign In
              </div>
              <div className="p-2 font-bold hover:underline hover:text-pink-600">
                Register
              </div>
            </div>
          </header>
        </>
        {children}
      </body>
    </html>
  );
}
